// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddCommentInput struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	AuthorID string  `json:"authorID"`
	Text     string  `json:"text"`
}

type Comment struct {
	ID        string             `json:"id"`
	PostID    string             `json:"postID"`
	ParentID  *string            `json:"parentID,omitempty"`
	AuthorID  string             `json:"authorID"`
	Text      string             `json:"text"`
	CreatedAt time.Time          `json:"createdAt"`
	Replies   *CommentConnection `json:"replies"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CreatePostInput struct {
	AuthorID        string `json:"authorID"`
	Title           string `json:"title"`
	Body            string `json:"body"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Post struct {
	ID              string             `json:"id"`
	AuthorID        string             `json:"authorID"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	CommentsEnabled bool               `json:"commentsEnabled"`
	CreatedAt       time.Time          `json:"createdAt"`
	UpdatedAt       time.Time          `json:"updatedAt"`
	Comments        *CommentConnection `json:"comments"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string `json:"cursor"`
	Node   *Post  `json:"node"`
}

type Query struct {
}
