package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/pidge31/posts-comments-service/internal/app"
	"github.com/pidge31/posts-comments-service/internal/graph/generated"
	"github.com/pidge31/posts-comments-service/internal/graph/model"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first *int, after *string) (*model.CommentConnection, error) {
	cursor, err := decodeCommentCursor(after)
	if err != nil {
		return nil, err
	}

	comments, nextCursor, err := r.commentService.ListComments(
		ctx,
		obj.PostID,
		&obj.ID,
		limitFromPointer(first),
		cursor,
	)
	if err != nil {
		return nil, err
	}

	return commentsToConnection(comments, nextCursor != nil), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	post, err := r.postService.CreatePost(ctx, app.CreatePostInput{
		AuthorID:        input.AuthorID,
		Title:           input.Title,
		Body:            input.Body,
		CommentsEnabled: input.CommentsEnabled,
	})
	if err != nil {
		return nil, err
	}

	return postToModel(*post), nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	comment, err := r.commentService.AddComment(ctx, app.AddCommentInput{
		PostID:   input.PostID,
		ParentID: input.ParentID,
		AuthorID: input.AuthorID,
		Text:     input.Text,
	})
	if err != nil {
		return nil, err
	}

	return commentToModel(*comment), nil
}

// SetPostCommentsEnabled is the resolver for the setPostCommentsEnabled field.
func (r *mutationResolver) SetPostCommentsEnabled(ctx context.Context, postID string, authorID string, enabled bool) (*model.Post, error) {
	post, err := r.postService.SetCommentsEnabled(ctx, postID, authorID, enabled)
	if err != nil {
		return nil, err
	}

	return postToModel(*post), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first *int, after *string) (*model.CommentConnection, error) {
	cursor, err := decodeCommentCursor(after)
	if err != nil {
		return nil, err
	}

	comments, nextCursor, err := r.commentService.ListComments(
		ctx,
		obj.ID,
		nil,
		limitFromPointer(first),
		cursor,
	)
	if err != nil {
		return nil, err
	}

	return commentsToConnection(comments, nextCursor != nil), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int, after *string) (*model.PostConnection, error) {
	cursor, err := decodePostCursor(after)
	if err != nil {
		return nil, err
	}

	posts, nextCursor, err := r.postService.ListPosts(ctx, limitFromPointer(first), cursor)
	if err != nil {
		return nil, err
	}

	return postsToConnection(posts, nextCursor != nil), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.postService.GetPost(ctx, id)
	if err != nil {
		return nil, err
	}

	return postToModel(*post), nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
