package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/pidge31/posts-comments-service/internal/app"
	"github.com/pidge31/posts-comments-service/internal/graph/generated"
	"github.com/pidge31/posts-comments-service/internal/graph/model"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first *int, after *string) (*model.CommentConnection, error) {
	cursor, err := decodeCommentCursor(after)
	if err != nil {
		return nil, err
	}

	page, err := loadCommentPage(
		ctx,
		r.commentService,
		app.CommentPageRequest{
			PostID:   obj.PostID,
			ParentID: &obj.ID,
			Limit:    limitFromPointer(first),
			Cursor:   cursor,
		},
	)
	if err != nil {
		return nil, err
	}

	return commentsToConnection(page.Comments, page.NextCursor != nil), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	post, err := r.postService.CreatePost(ctx, app.CreatePostInput{
		AuthorID:        input.AuthorID,
		Title:           input.Title,
		Body:            input.Body,
		CommentsEnabled: input.CommentsEnabled,
	})
	if err != nil {
		return nil, err
	}

	return postToModel(*post), nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string, authorID string) (bool, error) {
	if err := r.postService.DeletePost(ctx, postID, authorID); err != nil {
		return false, err
	}

	return true, nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input model.AddCommentInput) (*model.Comment, error) {
	comment, err := r.commentService.AddComment(ctx, app.AddCommentInput{
		PostID:   input.PostID,
		ParentID: input.ParentID,
		AuthorID: input.AuthorID,
		Text:     input.Text,
	})
	if err != nil {
		return nil, err
	}

	return commentToModel(*comment), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID string, authorID string) (bool, error) {
	if err := r.commentService.DeleteComment(ctx, commentID, authorID); err != nil {
		return false, err
	}

	return true, nil
}

// SetPostCommentsEnabled is the resolver for the setPostCommentsEnabled field.
func (r *mutationResolver) SetPostCommentsEnabled(ctx context.Context, postID string, authorID string, enabled bool) (*model.Post, error) {
	post, err := r.postService.SetCommentsEnabled(ctx, postID, authorID, enabled)
	if err != nil {
		return nil, err
	}

	return postToModel(*post), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first *int, after *string) (*model.CommentConnection, error) {
	cursor, err := decodeCommentCursor(after)
	if err != nil {
		return nil, err
	}

	page, err := loadCommentPage(
		ctx,
		r.commentService,
		app.CommentPageRequest{
			PostID: obj.ID,
			Limit:  limitFromPointer(first),
			Cursor: cursor,
		},
	)
	if err != nil {
		return nil, err
	}

	return commentsToConnection(page.Comments, page.NextCursor != nil), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int, after *string) (*model.PostPreviewConnection, error) {
	cursor, err := decodePostCursor(after)
	if err != nil {
		return nil, err
	}

	previews, nextCursor, err := r.postService.ListPosts(ctx, limitFromPointer(first), cursor)
	if err != nil {
		return nil, err
	}

	return postPreviewsToConnection(previews, nextCursor != nil), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.postService.GetPost(ctx, id)
	if err != nil {
		return nil, err
	}

	return postToModel(*post), nil
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	comment, err := r.commentService.GetComment(ctx, id)
	if err != nil {
		return nil, err
	}

	return commentToModel(*comment), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	if _, err := r.postService.GetPost(ctx, postID); err != nil {
		return nil, err
	}

	comments, unsubscribe, err := r.commentEventSubscriber.SubscribeToPostComments(ctx, postID)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.Comment, 1)

	go func() {
		defer unsubscribe()
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case comment, ok := <-comments:
				if !ok {
					return
				}

				select {
				case out <- commentToModel(comment):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
